//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Purchase_Id { get; set; }
        public Nullable<int> Purchase_Userid { get; set; }
        public Nullable<int> Purchase_Districtid { get; set; }
        public Nullable<int> Purchase_Pizzaid { get; set; }
        public Nullable<int> Purchase_Orderid { get; set; }
        public string Purchase_Number { get; set; }
        public Nullable<int> Purchase_Price { get; set; }
        public string Purchase_Date { get; set; }
        public string Purchase_No { get; set; }
    
        public virtual order order { get; set; }
        public virtual Pizza Pizza { get; set; }
    }
}
